---
name: Upload files to mil.ufl.edu

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - add-upload

jobs:
  upload:
    runs-on: self-hosted
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload files to web server
        run: |
          # Install lftp
          sudo apt-get install -y lftp
          # Upload web server contents
          lftp -c "open -u mil,${{ secrets.MIL_UFL_SFTP_PASS }} \
                        -p ${{ secrets.MIL_UFL_SFTP_PORT }} \
                        sftp://mil.ufl.edu; \
                        ls"
          lftp -c "open -u mil,${{ secrets.MIL_UFL_SFTP_PASS }} \
                        -p ${{ secrets.MIL_UFL_SFTP_PORT }} \
                        sftp://mil.ufl.edu; \
                        mirror -c \
                          --include='.*' \
                          --exclude='^\..*$' \
                          --only-newer --ignore-time \
                          -R --parallel \
                          . \
                          htdocs"
